version: '2'
services:
  fixedassetsuaa-postgresql:
    image: postgres:11.5
    volumes:
      - ~/volumes/jhipster/fixedAssetsUaa/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
    ports:
      - 585857:5432
