version: '2'
services:
  fixedassetsuaa-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/fixedAssetsUaa/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fixedAssetsUaa
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
